spring:
  redis:
    cluster:
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
        - 127.0.0.1:7006
      #跨集群执行命令时要遵循的最大重定向数
      max-attempts: 3
      #客户端连接超时时间（毫秒）
      connectionTimeout: 5000
      #客户端读写超时时间（毫秒）
      soTimeout: 6000
      password: 123456
    # 连接池
    jedis:
      pool:
        #连接池阻塞等待时间（负值表示没有限制）
        max-wait: 3000
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中最小空闲连接
        min-idle: 0